# Generated by Django 2.1.4 on 2019-01-16 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
