# Generated by Django 2.1.4 on 2019-01-10 10:23

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
            ],
            options={
                'verbose_name': '技能水平',
                'verbose_name_plural': '技能水平',
            },
        ),
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh_name', models.CharField(default='黄晔', max_length=10, verbose_name='中文名')),
                ('net_name', models.CharField(default='饕客', max_length=10, null=True, verbose_name='网名')),
                ('en_name', models.CharField(default='Tate', max_length=30, null=True, verbose_name='英文名')),
                ('head_img', models.ImageField(blank=True, default='', upload_to='img/%Y/%m/%d', verbose_name='头像')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, null=True, verbose_name='性别')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('addr', models.CharField(max_length=300, null=True, verbose_name='地址')),
                ('wechat', models.ImageField(blank=True, default='', upload_to='img/%Y/%m/%d', verbose_name='微信')),
                ('describe', DjangoUeditor.models.UEditorField(default='', verbose_name='自我描述')),
                ('resume', models.URLField(null=True, verbose_name='简历')),
                ('zh_name_useful', models.BooleanField(default=True, verbose_name='中文名字是否有效')),
                ('net_name_useful', models.BooleanField(default=True, verbose_name='网名是否有效')),
                ('en_name_useful', models.BooleanField(default=True, verbose_name='英文名字是否有效')),
                ('head_img_useful', models.BooleanField(default=True, verbose_name='头像是否有效')),
                ('age_useful', models.BooleanField(default=True, verbose_name='年龄是否有效')),
                ('sex_useful', models.BooleanField(default=True, verbose_name='性别是否有效')),
                ('phone_useful', models.BooleanField(default=True, verbose_name='电话号码是否有效')),
                ('email_useful', models.BooleanField(default=True, verbose_name='邮箱是否有效')),
                ('addr_useful', models.BooleanField(default=True, verbose_name='地址是否有效')),
                ('wechat_useful', models.BooleanField(default=True, verbose_name='微信是否有效')),
                ('describe_useful', models.BooleanField(default=True, verbose_name='自我描述是否有效')),
                ('resume_useful', models.BooleanField(default=True, verbose_name='简历是否有效')),
            ],
            options={
                'verbose_name': '关于我',
                'verbose_name_plural': '关于我',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.AddField(
            model_name='myinfo',
            name='skills',
            field=models.ManyToManyField(through='aboutme.Level', to='aboutme.Skill', verbose_name='技能'),
        ),
        migrations.AddField(
            model_name='level',
            name='myinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.MyInfo'),
        ),
        migrations.AddField(
            model_name='level',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.Skill'),
        ),
    ]
