# Generated by Django 2.1.4 on 2019-01-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20190103_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='head_img',
            field=models.ImageField(blank=True, default='', upload_to='img/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='名称'),
        ),
    ]
