# Generated by Django 2.1.4 on 2019-01-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_auto_20190104_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='wechat',
            field=models.ImageField(blank=True, default='', upload_to='img/%Y/%m/%d', verbose_name='微信'),
        ),
    ]
