# Generated by Django 2.1.4 on 2019-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_auto_20190111_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zan',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='addr_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='age_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='describe_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='email_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='en_name_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='head_img_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='net_name_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='phone_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='resume_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='sex_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='wechat_useful',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='zh_name_useful',
        ),
        migrations.AddField(
            model_name='myinfo',
            name='num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
