# Generated by Django 2.1.4 on 2019-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20190128_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
