# Generated by Django 2.1.4 on 2019-01-11 01:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20190110_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='博客内容'),
        ),
    ]
