# Generated by Django 2.1.4 on 2019-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20190128_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='zan_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
            preserve_default=False,
        ),
    ]
