# Generated by Django 2.1.4 on 2019-01-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20190111_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
