# Generated by Django 2.1.4 on 2019-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/default/head.jpg', upload_to='img/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
